# Generated by Django 5.1 on 2024-09-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateandReview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateandreview',
            name='user_id',
        ),
        migrations.AddField(
            model_name='rateandreview',
            name='tittle',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
